# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-01-23 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransaction',
            name='reference',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
