# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-01-23 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_accounttransaction_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_holding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounttransaction',
            name='phone_number',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
