# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-01-23 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220123_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
