# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-10 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMoneyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reference', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=32)),
                ('origin', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('SUCCESSFUL', 'SUCCESSFUL'), ('FAILED', 'FAILED')], max_length=15)),
                ('request', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mobile_money_request',
            },
        ),
    ]
