# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-01-21 03:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier', '0007_supplier_balance'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_initiated', models.DateTimeField()),
                ('transaction_reference', models.CharField(max_length=255)),
                ('payment_method', models.CharField(choices=[('CASH', 'CASH'), ('BANK', 'BANK'), ('MOBILE MONEY', 'MOBILE MONEY')], max_length=16)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('SUCCESSFUL', 'SUCCESSFUL'), ('FAILED', 'FAILED')], max_length=15)),
                ('balance_before', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=32)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True)),
                ('request', models.TextField()),
                ('response', models.TextField(blank=True, null=True)),
                ('response_date', models.DateTimeField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier')),
            ],
            options={
                'db_table': 'member_payment_transaction',
            },
        ),
    ]
