# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-27 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrodealer', '0003_auto_20201027_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrodealer',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
