# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-30 19:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0002_systemsettings_mobile_money_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agrodealer', '0004_auto_20201027_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgroDealerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agrodealer_category',
            },
        ),
        migrations.CreateModel(
            name='AgroDealerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agrodealer_item',
            },
        ),
        migrations.CreateModel(
            name='AgroDealerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'agrodealer_user',
            },
        ),
        migrations.AddField(
            model_name='agrodealer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agrodealer',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agrodealer',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conf.County'),
        ),
        migrations.AddField(
            model_name='agrodealer',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conf.District'),
        ),
        migrations.AddField(
            model_name='agrodealer',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agrodealer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='agrodealer',
            name='sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conf.SubCounty'),
        ),
        migrations.AddField(
            model_name='agrodealer',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agrodealeruser',
            name='agrodealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrodealer.AgroDealer'),
        ),
        migrations.AddField(
            model_name='agrodealeruser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agrodealeritem',
            name='agrodealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agrodealer.AgroDealer'),
        ),
        migrations.AddField(
            model_name='agrodealeritem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrodealer.AgroDealerCategory'),
        ),
        migrations.AddField(
            model_name='agrodealercategory',
            name='agrodealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agrodealer.AgroDealer'),
        ),
    ]
