# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-01 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrodealer', '0006_auto_20201110_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrodealeritem',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='agrodealeritem',
            unique_together=set([('name', 'agrodealer', 'price')]),
        ),
    ]
