# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 01:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=12)),
                ('message', models.TextField()),
                ('remark', models.CharField(blank=True, max_length=160, null=True)),
                ('sent_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='PENDING', max_length=12)),
                ('response', models.TextField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'outgoing_message',
            },
        ),
    ]
