# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-10 14:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_auto_20201030_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplieruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
