# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-10 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_auto_20201110_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='supplier/logo/'),
        ),
    ]
