# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-01-22 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_supplier_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='item',
            name='out_of_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='supplier_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
