# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-01-22 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0008_auto_20220122_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='status',
            new_name='is_active',
        ),
    ]
