# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-01-23 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('supplier', '0010_item_mark_up_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
    ]
