# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='mobile_money_payment',
            field=models.BooleanField(default=0),
        ),
    ]
