# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-10 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0002_systemsettings_mobile_money_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Code'),
        ),
    ]
