# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-30 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_supplyorder_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('CANCELLED', 'CANCELLED'), ('SHIPPED', 'SHIPPED'), ('DELIVERED', 'DELIVERED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=255),
        ),
    ]
