# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-01 19:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier', '0004_auto_20201030_1208'),
        ('agrodealer', '0005_auto_20201030_2202'),
        ('order', '0004_auto_20201030_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_reference', models.CharField(blank=True, max_length=255)),
                ('order_number', models.CharField(blank=True, max_length=255)),
                ('order_reference', models.CharField(blank=True, max_length=255)),
                ('order_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('CANCELLED', 'CANCELLED'), ('SHIPPED', 'SHIPPED'), ('DELIVERED', 'DELIVERED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=255)),
                ('order_date', models.DateTimeField()),
                ('accept_date', models.DateTimeField(blank=True, null=True)),
                ('reject_date', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=120, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_order',
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('CANCELLED', 'CANCELLED'), ('SHIPPED', 'SHIPPED'), ('DELIVERED', 'DELIVERED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=255)),
                ('order_date', models.DateTimeField()),
                ('accept_date', models.DateTimeField(blank=True, null=True)),
                ('reject_date', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=120, null=True)),
                ('ship_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_accept_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_reject_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_reject_reason', models.CharField(blank=True, max_length=120, null=True)),
                ('collect_date', models.DateTimeField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.Item')),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='agrodealer.AgroDealerItem')),
            ],
            options={
                'db_table': 'customer_order_item',
            },
        ),
    ]
