# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-01 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_customerorder_customerorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorderitem',
            name='item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='agrodealer.AgroDealerItem'),
        ),
        migrations.AlterField(
            model_name='customerorderitem',
            name='order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='order.CustomerOrder'),
        ),
    ]
