# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-10 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrodealer', '0005_auto_20201030_2202'),
        ('order', '0008_auto_20201110_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='agro_dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agrodealer.AgroDealer'),
        ),
    ]
