# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-10 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20201110_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyorder',
            name='agro_dealer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='agrodealer.AgroDealer'),
        ),
        migrations.AlterField(
            model_name='supplyorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID'), ('CONFIRMED', 'CONFIRMED'), ('CANCELLED', 'CANCELLED'), ('SHIPPED', 'SHIPPED'), ('DELIVERED', 'DELIVERED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=255),
        ),
    ]
