# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-01-18 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20201110_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyorder',
            name='agro_dealer',
        ),
    ]
