# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-01-18 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_remove_supplyorder_agro_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID'), ('CONFIRMED', 'CONFIRMED'), ('CANCELLED', 'CANCELLED'), ('SHIPPED', 'SHIPPED'), ('DELIVERED', 'DELIVERED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=255),
        ),
    ]
