# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-01-23 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20220123_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyorder',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
